name: _
publish_to: none

workspace:
  - supernova
  - supernova_flutter
  - supernova_lints

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependency_overrides:
  chrono:
    git:
      url: https://github.com/JonasWanke/chrono.git
      path: chrono
      ref: 3c8bf3a9433737a2ba6b48b7ccc3460dfde2fcec
