targets:
  $default:
    builders:
      freezed:
        options:
          union_key: _type
      json_serializable:
        options:
          explicit_to_json: true
          generic_argument_factories: true
