name: supernova_lints
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dart_code_metrics:
    git:
      url: https://github.com/JonasWanke/dart-code-metrics.git
      ref: 42b9a1d6f8baac052411cf68448d29a82c621066
