name: Build & Lint

on:
  pull_request:
  schedule:
    - cron: 0 4 * * *

env:
  JAVA_VERSION: 12.x

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutterChannel: [stable, beta]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutterChannel }}

      - run: dart pub get
        working-directory: supernova
      - run: dart analyze
        working-directory: supernova

      - run: flutter pub get
        working-directory: supernova_flutter
      - run: flutter analyze
        working-directory: supernova_flutter
